### ISSUE TITLE
Only last entry per proxy/echo config in Caddyfile being started

### ISSUE THREAD

**Issue by pieterlouw** [pieterlouw/caddy-net#3]
This is in reference to problem mentioned in #2.

When multiple entries in Caddyfile is specified then only the last entry is started by Caddy

**Comment by orware** [comment]
Thanks Pieter! Happy to give it a try afterward ;-).

**Comment by RX14** [comment]
Hi, i'm considering using caddy-net to terminate SSL in front of my znc IRC bouncer, to take advantage of the automatic tls renewal. It would be great if caddy-net supported multiple proxies so I didn't need to have multiple caddy processes. I'd be happy to make a PR myself, but unfortunately I don't know go, so it might be easier if you did the PR yourself.

**Comment by pieterlouw** [comment]
Hi, 
Apologies for sitting on this for longer than I should. My work and life commitments were a bit hectic these last few weeks but are settling down - I should probably be able to have a look at this in the next week or so.

**Comment by RX14** [comment]
No rush! It turns out that I don't actually need this feature yet. You needn't feel any pressure to work on this.

**Comment by pieterlouw** [comment]
Hi, 
I have fixed the issue. 
To use the fixed version, please redownload Caddy with the net plugin

Thanks for your patience!

Pieter

**Comment by orware** [comment]
No problem Pieter, thank you! I'll give it a shot in the next day or so ;-).
